import type { Team } from "./team";
import type { Position } from "./position";
import type { Supervisor } from "./supervisor";
import type { Department } from "./department";
import type { Permission } from "./permission";
import type { DiscordInfo } from "./discord-info";
import type { Censure } from "./censure";
import type { Strike } from "./strike";
import type { Pip } from "./pip";

export type StaffFile = {
  id: string;
  name: string;
  personalEmail: string;
  companyEmail: string;
  photoLink: string;
  phone: string;
  legalSex: string;
  gender: string;
  ethnicity: string;
  appStatus: string;
  activtyStatus: string;
  alumni: boolean;
  createdAt: Date;
  updatedAt: Date | null;
  team?: Team | null;
  teamId: string | null;
  positions?: Position[];
  supervisor?: Supervisor;
  supervisorId: string;
  department?: Department | null;
  departmentId: string | null;
  permissions?: Permission | null;
  permissionId: string | null;
  discordInfo?: DiscordInfo | null;
  discordInfoId: string | null;
  censures?: Censure[];
  strikes?: Strike[];
  pips?: Pip[];
};
